common	crt.sca$        rem June 28,1979
common	crt.sca.row$
common  crt.sca.column$
common  crt.clear$
common  crt.foreground$
common  crt.background$
common  crt.clear.foreground$
common  crt.home.cursor$
common  crt.up.cursor$
common  crt.down.cursor$
common  crt.right.cursor$
common  crt.left.cursor$
common  crt.backspace$
common  crt.alarm$
common  crt.eol$
common  crt.eos$
common  crt.insert.line$
common  crt.delete.line$
common  crt.init.io.port.data$
common  crt.init.console.data$
common  crt.order.row.col%
common  crt.order.col.row%
common  crt.sca.order%
common  crt.sca.hex%
common  crt.sca.decimal%
common  crt.sca.format%
common  crt.rows%,crt.columns%
common  crt.row.xlate%(1)
common  crt.column.xlate%(1)
common  crt.true%
common  crt.false%
common  crt.file%
common  crt.blank$
common  crt.using$
common  crt.msg.header$
common  crt.msg.trailer$
common  crt.digits%(1)
common  crt.format$
common  crt.mult.backspaces$(1)
common  crt.back.count$
common  crt.ctl.xlate$
common  crt.key.prefix%
common  crt.key.xlate$

