dim ded.sys.used%		(pr1.max.sys.eds%)  rem 9/26/79
dim ded.sys.acct.no%		(pr1.max.sys.eds%)
dim ded.sys.chk.cat%		(pr1.max.sys.eds%)
dim ded.sys.desc$		(pr1.max.sys.eds%)
dim ded.sys.limit		(pr1.max.sys.eds%)
dim ded.sys.limit.used% 	(pr1.max.sys.eds%)
dim ded.sys.factor		(pr1.max.sys.eds%)
dim ded.sys.earn.ded$		(pr1.max.sys.eds%)
dim ded.sys.amt.percent$	(pr1.max.sys.eds%)
dim ded.sys.exclusion%		(pr1.max.sys.eds%)
dim ded.fwt.mar.cutoff		(07)
dim ded.fwt.sin.cutoff		(07)
dim ded.fwt.mar.percent 	(07)
dim ded.fwt.sin.percent 	(07)
