%NOLIST
	REM ******************************************************************\
	    *								                                 *\
	    *	   OECREFIL.BAS       CREDIT CARD FILE CONTROL MODULE	     *\
	    *								                                 *\
	    ******************************************************************

	REM ***  OPEN CREDIT CARD VERIFICATION FILE  ***

80600	FILE$=PR1.CRED.DRV$+"OECREFIL.101" : N%=7 : GOSUB 85200
	RETURN

80610	ERROR$="UNABLE TO OPEN CREDIT CARD VERIFICATION FILE"
	GOTO 85000

	REM ***  READ CREDIT CARD FILE	***

80620	READ #7; C1.CREDNO$, C1.ORDNO$, C1.CREDNAME$, C1.EXPIRY$, \
		C1.CUSTNAME$, C1.CUSTADD1$, C1.CUSTADD2$, C1.CUSTADD3$, \
		C1.POSTCODE$, C1.CUSTTEL$, C1.ORDER.TOTAL$
	RETURN

80630	ERROR$="UNABLE TO READ CREDIT CARD VERIFICATION FILE"
	GOTO 85000

	REM ***  WRITE CREDIT CARD FILE  ***

80640	C1.FILLER$     ="                              "
	C1.NUMFILL$    ="0000000000"
	C1.CREDNO$     =LEFT$(C1.CREDNO$+C1.FILLER$,14)
	C1.ORDNO$      =RIGHT$(C1.NUMFILL$+C1.ORDNO$,5)
	C1.CREDNAME$   =LEFT$(C1.CREDNAME$+C1.FILLER$,16)
	C1.CUSTNAME$   =LEFT$(C1.CUSTNAME$+C1.FILLER$,30)
	C1.CUSTADD1$   =LEFT$(C1.CUSTADD1$+C1.FILLER$,30)
	C1.CUSTADD2$   =LEFT$(C1.CUSTADD2$+C1.FILLER$,30)
	C1.CUSTADD3$   =LEFT$(C1.CUSTADD3$+C1.FILLER$,24)
	C1.POSTCODE$   =LEFT$(C1.POSTCODE$+C1.FILLER$,9)
	C1.CUSTTEL$    =LEFT$(C1.CUSTTEL$+C1.FILLER$,13)
	C1.ORDER.TOTAL$=RIGHT$(C1.NUMFILL$+C1.ORDER.TOTAL$,10)
	PRINT #7; C1.CREDNO$, C1.ORDNO$, C1.CREDNAME$, C1.EXPIRY$, \
		C1.CUSTNAME$, C1.CUSTADD1$, C1.CUSTADD2$, C1.CUSTADD3$, \
		C1.POSTCODE$, C1.CUSTTEL$, C1.ORDER.TOTAL$
	RETURN

80645	ERROR$="UNABLE TO WRITE CREDIT CARD VERIFICATION FILE"
	GOTO 85000

	REM ***  CREATE CREDIT CARD VERIFICATION FILE  ***

80650	FILE$=PR1.CRED.DRV$+"OECREFIL.101" : N%=7 : GOSUB 85400
	RETURN

80655	ERROR$="UNABLE TO CREATE CREDIT CARD VERIFICATION FILE"
	GOTO 85000
%LIST
