rem %NOLIST
	REM ******************************************************************\
	    *					                             			     *\
	    *	   OECREPRT.BAS      SORTED CREDIT CARD FILE CONTROL MODULE  *\
	    *								                                 *\
	    ******************************************************************

	REM ***  OPEN CREDIT CARD VERIFICATION FILE  ***

80800	FILE$=PR1.CRED.DRV$+"OECREPRT.101" : N%=20 : GOSUB 85200
	RETURN

80810	ERROR$="UNABLE TO OPEN SORTED CREDIT CARD PRINT FILE"
	GOTO 85000

	REM ***  READ CREDIT CARD FILE	***

80820	READ #20; C1.CREDNO$, C1.ORDNO$, C1.CREDNAME$, C1.EXPIRY$, \
		C1.CUSTNAME$, C1.CUSTADD1$, C1.CUSTADD2$, C1.CUSTADD3$, \
		C1.POSTCODE$, C1.CUSTTEL$, C1.ORDER.TOTAL$
	RETURN

80830	ERROR$="UNABLE TO READ SORTED CREDIT CARD FILE"
	GOTO 85000

	REM ***  CREATE CREDIT CARD VERIFICATION PRINT FILE  ***

80850	FILE$=PR1.CRED.DRV$+"OECREPRT.101" : N%=20 : GOSUB 85400
	RETURN

80855	ERROR$="UNABLE TO CREATE SORTED CREDIT CARD VERIFICATION FILE"
	GOTO 85000
rem %LIST
