rem %NOLIST
	REM ******************************************************************\
	    *								                                 *\
	    *	   OEDISFIL.BAS       DISPATCH NOTE FILE CONTROL MODULE      *\
	    *								                                 *\
	    ******************************************************************

	REM ***  OPEN DISPATCH NOTE FILE  ***

80300	FILE$=PR1.DISP.DRV$+"OEDISFIL.101" : N%=4 : GOSUB 85200
	RETURN

80310	ERROR$="UNABLE TO OPEN DISPATCH NOTE FILE"
	GOTO 85000

	REM ***  READ DISPATCH NOTE FILE  ***

80320	READ #4; D1.ORDNO%, D1.RECTYPE%
	RETURN

80322	READ #4; D1.CUSTNAME$, D1.CUSTADD1$, D1.CUSTADD2$, D1.CUSTADD3$,\
		D1.POSTCODE$, D1.CUSTORDNO$, D1.DATE$, D1.PAY%
	RETURN

80324	READ #4; D1.PARTNO$, D1.PARTDESC$, D1.QUANTITY%, D1.INSTOCK%
	RETURN

80330	ERROR$="UNABLE TO READ DISPATCH NOTE FILE"
	GOTO 85000

	REM ***  WRITE DISPATCH NOTE RECORD TYPE 1  ***

80340	PRINT #4; D1.ORDNO%, D1.RECTYPE%, D1.CUSTNAME$, D1.CUSTADD1$,\
		D1.CUSTADD2$, D1.CUSTADD3$, D1.POSTCODE$, D1.CUSTORDNO$,\
		D1.DATE$, D1.PAY%
	RETURN

80345	ERROR$="UNABLE TO WRITE DISPATCH NOTE RECORD TYPE 1"
	GOTO 85000

	REM ***  WRITE DISPATCH NOTE RECORD TYPE 2  ***

80350	PRINT #4; D1.ORDNO%, D1.RECTYPE%, D1.PARTNO$, D1.PARTDESC$,\
		D1.QUANTITY%, D1.INSTOCK%
	RETURN

80355	ERROR$="UNABLE TO WRITE DISPATCH NOTE RECORD TYPE 2"
	GOTO 85000

	REM ***  CREATE DISPATCH NOTE FILE  ***

80360	FILE$=PR1.DISP.DRV$+"OEDISFIL.101" : N%=4 : GOSUB 85400
	RETURN

80365	ERROR$="UNABLE TO CREATE DISPATCH NOTE FILE"
	GOTO 85000
rem %LIST
