rem %NOLIST
	REM ******************************************************************\
	    *															     *\
	    *	   OEPR1FIL.BAS       PARAMETER FILE 1 CONTROL MODULE	     *\
	    *								     							 *\
	    ******************************************************************

	REM ***  OPEN PARAMETER FILE 1	***

80000	IF END #1 THEN 80010
	FILE$="A:OEPR1FIL.101" : M%=218 : N%=1 : GOSUB 85100
	RETURN

80010	ERROR$="UNABLE TO OPEN PARAMETER FILE 1"
	GOTO 85000

	REM ***  READ PARAMETER FILE 1	***

80020	IF END #1 THEN 80030
	READ #1,1; PR1.PASSWORD$(1), PR1.PASSWORD$(2), PR1.PASSWORD$(3),\
		PR1.CREDCARD.CODE%(1), PR1.CREDCARD.CODE%(2),\
		PR1.CREDCARD.CODE%(3), PR1.CREDCARD.CODE%(4),\
		PR1.CREDCARD.NAME$(1), PR1.CREDCARD.NAME$(2),\
		PR1.CREDCARD.NAME$(3), PR1.CREDCARD.NAME$(4), PR1.ORDNO.GEN%,\
		PR1.INVNO.GEN%, PR1.DISP.DRV$, PR1.SUSP.DRV$, PR1.INV.DRV$,\
		PR1.CRED.DRV$, PR1.STOCKFIL.IND%, PR1.STOCKFIL.DRV$,\
		PR1.STOCKFIL.NAME$, PR1.CUSTFIL.IND%, PR1.CUSTFIL.DRV$,\
		PR1.CUSTFIL.NAME$, PR1.SALESFIL.IND%, PR1.SALESFIL.DRV$,\
		PR1.SALESFIL.NAME$, PR1.VDUDEF.NAME$
	RETURN

80030	ERROR$="UNABLE TO READ PARAMETER FILE 1"
	GOTO 85000

	REM ***  WRITE PARAMETER FILE 1  ***

80040	PRINT #1,1; PR1.PASSWORD$(1), PR1.PASSWORD$(2), PR1.PASSWORD$(3),\
		PR1.CREDCARD.CODE%(1), PR1.CREDCARD.CODE%(2),\
		PR1.CREDCARD.CODE%(3), PR1.CREDCARD.CODE%(4),\
		PR1.CREDCARD.NAME$(1), PR1.CREDCARD.NAME$(2),\
		PR1.CREDCARD.NAME$(3), PR1.CREDCARD.NAME$(4), PR1.ORDNO.GEN%,\
		PR1.INVNO.GEN%, PR1.DISP.DRV$, PR1.SUSP.DRV$, PR1.INV.DRV$,\
		PR1.CRED.DRV$, PR1.STOCKFIL.IND%, PR1.STOCKFIL.DRV$,\
		PR1.STOCKFIL.NAME$, PR1.CUSTFIL.IND%, PR1.CUSTFIL.DRV$,\
		PR1.CUSTFIL.NAME$, PR1.SALESFIL.IND%, PR1.SALESFIL.DRV$,\
		PR1.SALESFIL.NAME$, PR1.VDUDEF.NAME$
	RETURN

80045	ERROR$="UNABLE TO WRITE PARAMETER FILE 1"
	GOTO 85000

	REM ***  CREATE PARAMETER FILE 1  ***

80050	FILE$="A:OEPR1FIL.101" : M%=218 : N%=1 : GOSUB 85300
	RETURN

80055	ERROR$="UNABLE TO CREATE PARAMETER FILE 1"
	GOTO 85000
rem %LIST
