rem	Nov.  8, 1979	     -----------------------------------
rem
rem    all functions needed for  DMS  except CRT characteristics definition
rem    and screen attribute and clear functions
rem
rem-------------------------------------------------------------
%include b:zdmssca
%include b:zdmsmsg
%include b:zdmsemsg
%include b:zdmslit
%include b:zdmsput
%include b:zdmsptal
%include b:zdmsget
