ded.fwt.used%,\ 	      rem   10/04/79
ded.fwt.acct.no%,ded.fwt.allowance.amt,\
ded.fwt.mar.cutoff(01),ded.fwt.mar.percent(01),\
ded.fwt.mar.cutoff(02),ded.fwt.mar.percent(02),\
ded.fwt.mar.cutoff(03),ded.fwt.mar.percent(03),\
ded.fwt.mar.cutoff(04),ded.fwt.mar.percent(04),\
ded.fwt.mar.cutoff(05),ded.fwt.mar.percent(05),\
ded.fwt.mar.cutoff(06),ded.fwt.mar.percent(06),\
ded.fwt.mar.cutoff(07),ded.fwt.mar.percent(07),\
ded.fwt.sin.cutoff(01),ded.fwt.sin.percent(01),\
ded.fwt.sin.cutoff(02),ded.fwt.sin.percent(02),\
ded.fwt.sin.cutoff(03),ded.fwt.sin.percent(03),\
ded.fwt.sin.cutoff(04),ded.fwt.sin.percent(04),\
ded.fwt.sin.cutoff(05),ded.fwt.sin.percent(05),\
ded.fwt.sin.cutoff(06),ded.fwt.sin.percent(06),\
ded.fwt.sin.cutoff(07),ded.fwt.sin.percent(07),\
ded.swt.used%,ded.swt.acct.no%,\
ded.lwt.used%,ded.lwt.acct.no%,\
ded.fica.used%,\
ded.fica.acct.no%,ded.fica.rate,ded.fica.limit,\
ded.co.fica.used%,\
ded.co.fica.acct.no%,ded.co.fica.rate,ded.co.fica.limit,\
ded.sdi.used%,\
ded.sdi.acct.no%,ded.sdi.rate,ded.sdi.limit,\
ded.co.futa.used%,\
ded.co.futa.acct.no%,ded.co.futa.rate,ded.co.futa.limit,\
ded.co.futa.max.credit,\
ded.co.sui.used%,\
ded.co.sui.acct.no%,ded.co.sui.rate,ded.co.sui.limit,\
ded.eic.used%,\
ded.eic.acct.no%,ded.eic.rate,ded.eic.limit,\
ded.eic.excess.rate,ded.eic.excess.limit,\
ded.sys.used%(01),\
ded.sys.acct.no%(01),ded.sys.chk.cat%(01),ded.sys.desc$(01),\
ded.sys.limit(01),ded.sys.factor(01),ded.sys.earn.ded$(01),\
ded.sys.amt.percent$(01),ded.sys.exclusion%(01),ded.sys.limit.used%(01),\
ded.sys.used%(02),\
ded.sys.acct.no%(02),ded.sys.chk.cat%(02),ded.sys.desc$(02),\
ded.sys.limit(02),ded.sys.factor(02),ded.sys.earn.ded$(02),\
ded.sys.amt.percent$(02),ded.sys.exclusion%(02),ded.sys.limit.used%(02),\
ded.sys.used%(03),\
ded.sys.acct.no%(03),ded.sys.chk.cat%(03),ded.sys.desc$(03),\
ded.sys.limit(03),ded.sys.factor(03),ded.sys.earn.ded$(03),\
ded.sys.amt.percent$(03),ded.sys.exclusion%(03),ded.sys.limit.used%(03),\
ded.sys.used%(04),\
ded.sys.acct.no%(04),ded.sys.chk.cat%(04),ded.sys.desc$(04),\
ded.sys.limit(04),ded.sys.factor(04),ded.sys.earn.ded$(04),\
ded.sys.amt.percent$(04),ded.sys.exclusion%(04),ded.sys.limit.used%(04),\
ded.sys.used%(05),\
ded.sys.acct.no%(05),ded.sys.chk.cat%(05),ded.sys.desc$(05),\
ded.sys.limit(05),ded.sys.factor(05),ded.sys.earn.ded$(05),\
ded.sys.amt.percent$(05),ded.sys.exclusion%(05),ded.sys.limit.used%(05)
